services:
  gira-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gira-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - gira-sqldata:/var/opt/mssql
    restart: unless-stopped

volumes:
  gira-sqldata:
